import GlowingDotsBackground from "@/components/bg/GlowingDotsBackground";
import ClientLoadingManager from "@/components/ClientLoadingManager";
import SideBar from "@/components/sidebar/SideBar";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Montserrat, Poppins } from "next/font/google";
import React from "react";
import "./globals.css";

const LoadingOverlay = dynamic(() => import("@/components/ui/LoadingOverlay"), {
  ssr: false,
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Gelo Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${montserrat.className} dark`}>
        <ClientLoadingManager>
          <div className="flex gap-5">
            <SideBar />
            <div className="flex-1 px-4 py-2">{children}</div>
          </div>
        </ClientLoadingManager>
        <GlowingDotsBackground />
        <Toaster />
      </body>
    </html>
  );
}
